deepspeed: 'configs/deepspeed/zero3.json'
dataset_path: "path_to/train_data.jsonl"
model_name_or_path: "OpenGVLab/InternVL2-8B"
bias_model_path: "OpenGVLab/InternVL2-8B"
output_dir: null  # to be set by the script
freeze_llm: false
freeze_backbone: true
freeze_mlp: false
grad_checkpoint: true
gradient_checkpointing: true
drop_path_rate: 0.1
max_dynamic_patch: 6
conv_style: "internlm2-chat"
dynamic_image_size: true
use_thumbnail: true
num_train_epochs: 1
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 2
save_strategy: "steps"
save_steps: 100
save_total_limit: 10
learning_rate: 1e-5
weight_decay: 0.05
adam_beta2: 0.98
warmup_ratio: 0.1
lr_scheduler_type: "cosine"
logging_steps: 10
report_to: tensorboard
max_length: 4096
bf16: true
tf32: true
logging_first_step: true
remove_unused_columns: false